#!/usr/bin/env bash
python main.py --cid 38 --save_name 隶书-赵之谦 --total_num 6841
python main.py --cid 7 --save_name 张即之 --total_num 6662
python main.py --cid 32 --save_name 张猛龙碑 --total_num 6817
python main.py --cid 27 --save_name 智永 --total_num 6576
python main.py --cid 6 --save_name 柳公权 --total_num 6196
python main.py --cid 30 --save_name 标楷体-手写 --total_num 6677
python main.py --cid 40 --save_name 欧阳询-九成宫 --total_num 6901
python main.py --cid 39 --save_name 欧阳询-皇甫诞 --total_num 6999
python main.py --cid 2 --save_name 沈尹默 --total_num 6809
python main.py --cid 37 --save_name 美工-崩云体 --total_num 6391
python main.py --cid 42 --save_name 美工-瘦颜体 --total_num 6231
python main.py --cid 8 --save_name 虞世南 --total_num 7036
python main.py --cid 29 --save_name 行书-傅山 --total_num 9761
python main.py --cid 12 --save_name 行书-王壮为 --total_num 8639
python main.py --cid 11 --save_name 行书-王铎 --total_num 10818
python main.py --cid 10 --save_name 行书-米芾 --total_num 7699
python main.py --cid 43 --save_name 行书-赵孟俯 --total_num 6655
python main.py --cid 35 --save_name 行书-郑板桥 --total_num 7794
python main.py --cid 34 --save_name 行书-集字圣教序 --total_num 7273
python main.py --cid 36 --save_name 褚遂良 --total_num 7251
python main.py --cid 3 --save_name 赵之谦 --total_num 6567
python main.py --cid 1 --save_name 赵孟俯三门记体 --total_num 7195
python main.py --cid 31 --save_name 隶书-伊秉绶 --total_num 7486
python main.py --cid 23 --save_name 隶书-何绍基 --total_num 8020
python main.py --cid 25 --save_name 隶书-邓石如 --total_num 6291
python main.py --cid 24 --save_name 隶书-金农 --total_num 10341
python main.py --cid 41 --save_name 颜真卿-颜勤礼碑 --total_num 7006
python main.py --cid 5 --save_name 颜真卿多宝塔体 --total_num 6333
python main.py --cid 4 --save_name 魏碑 --total_num 6891